Prevent Fuzzilli from generating async arrow functions during mutation
Summary:
Original Author: edq@fb.com
Original Git: e03064e719d775d8be200a43d4d3a3d4e57be0b2

Hermes currently does not support async arrow functions, so let's prevent `AsyncArrowFunctionGenerator` from being selected by the `CodeGenMutator`

```test.js

async function asyncFunction() {
  console.log('test');
}

(async () => {
    console.log(await asyncFunction());
})();
```

```./hermes test.js
test.js:5:2: error: async functions are unsupported
(async () => {
 ^~~~~~~~~~~~~
Emitted 1 errors. exiting.
```

Original Revision: D39601546

Reviewed By: tmikov

Differential Revision: D41240816

fbshipit-source-id: c0292114ed5266e372f4405b7514851c3db2d0a3